name: Copilot setup steps

# Automatically run the setup steps when they are changed to allow for easy validation,
# and to allow manual testing through by triggering in the repository's "Actions" tab
# ref: https://docs.github.com/en/copilot/how-tos/agents/copilot-coding-agent/customizing-the-development-environment-for-copilot-coding-agent
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      BUNDLE_PATH: "vendor/bundle"
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_GEMFILE: Gemfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ">=22.18.0"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install Node dependencies
        run: npm install

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Display environment info
        run: |
          echo "=== Environment Setup Complete ==="
          echo "✅ Node Version: $(node --version)"
          echo "✅ NPM Version: $(npm --version)"
          echo "✅ Ruby Version: $(ruby --version)"
          echo "✅ Jekyll Version: $(bundle exec jekyll --version || echo 'jekyll not available')"
          echo "✅ Bundler Version: $(bundle --version)"
          echo "✅ Installed Gems (top-level):"
          bundle list --paths | sed -n '1,200p' || true
          echo "=== Ready for Copilot Coding Agent Session ==="
